### ISSUE TITLE
Some robots configuration files try to run parametricCalibratorETH on CAN devices, in particular on the head

### ISSUE THREAD

**Issue by traversaro** [robotology/robots-configuration#36]
Complete list of robots that need a fix:  
* [x] `iCubGenova02` https://github.com/robotology/robots-configuration/blob/master/iCubGenova02/calibrators/head-calib.xml 
* [x] `iCubGenova06` https://github.com/robotology/robots-configuration/blob/master/iCubGenova06/calibrators/head-calib.xml
 * [x] `iCubNancy01` https://github.com/robotology/robots-configuration/blob/master/iCubNancy01/calibrators/head-calib.xml 
 * [x] `iCubTwente01` https://github.com/robotology/robots-configuration/blob/master/iCubTwente01/calibrators/head-calib.xml → icebox ❄️
 * [x] `iCubDarmstad01` https://github.com/robotology/robots-configuration/blob/master/iCubDarmstadt01/calibrators/head-calib.xml → icebox ❄️
* [x] `iCubSheffield01` https://github.com/robotology/robots-configuration/blob/master/iCubSheffield01/calibrators/head-calib.xml → icebox ❄️
* [x] `iCubNottingham01` https://github.com/robotology/robots-configuration/blob/master/iCubNottingham01/calibrators/head-calib.xml → icebox ❄️

Original issue: https://github.com/robotology/icub-main/issues/388 
Related issue: https://github.com/robotology/icub-main/issues/240 

cc @randaz81 @davidetome

**Comment by gabrielenava** [comment]
concerning iCubNancy01, this problem should be fixed in this PR: https://github.com/robotology/robots-configuration/pull/34/commits/6ea22ece5d6e59f7eabe0a4c6bb4b28677c7d921

**Comment by traversaro** [comment]
From this line https://github.com/robotology/robots-configuration/blob/f586480195638ca7e0e23452dfd1adf1aa9c2668/iCubNancy01/calibrators/head-calib.xml#L3 it seems that it is still trying to use the `parametricCalibratorEth` device for a Can device, so I don't think it was solved at all.

**Comment by traversaro** [comment]
cc @valegagge that modified several of this files in the recent past.

**Comment by valegagge** [comment]
The changes I done are regarding device name only.

As I already wrote here (https://github.com/robotology/icub-support/issues/500),  the problem is due to the wrong device of calibration written in the configuration files.

**Comment by traversaro** [comment]
This is probably something that it could be handled by team fix @marcoaccame .

**Comment by pattacini** [comment]
We just need to address the following robots:
- iCubGenova02
- iCubGenova06
- iCubNancy01

**Comment by davidetome** [comment]
Done w/ this PR : 

- https://github.com/robotology/robots-configuration/pull/553

`iCubGenova02` become a full ETH robot in the meanwhile

cc @pattacini @traversaro

**Comment by pattacini** [comment]
PR merged 🚀
